"""Add field_name, old_value, new_value to operation_logs

Revision ID: 58e20ee29f6a
Revises: add_operation_logs
Create Date: 2025-12-25 10:17:21.599582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58e20ee29f6a'
down_revision = 'add_operation_logs'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('operation_logs', sa.Column('field_name', sa.String(length=100), nullable=True))
    op.add_column('operation_logs', sa.Column('old_value', sa.Text(), nullable=True))
    op.add_column('operation_logs', sa.Column('new_value', sa.Text(), nullable=True))
    op.create_index(op.f('ix_operation_logs_id'), 'operation_logs', ['id'], unique=False)
    op.alter_column('project_non_dev_works', 'work_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'other_work'"))
    op.alter_column('projects', 'priority',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               nullable=False)
    op.alter_column('projects', 'label_path',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.create_foreign_key(op.f('fk_projects_creator_id_users'), 'projects', 'users', ['creator_id'], ['id'])
    op.alter_column('users', 'email',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.alter_column('users', 'full_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('users', 'phone',
               existing_type=sa.TEXT(),
               type_=sa.String(length=30),
               existing_nullable=True)
    op.alter_column('users', 'avatar_key',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('work_items', 'label_path',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.alter_column('work_items', 'estimated_hours',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.drop_index('idx_work_item_sort_parent', table_name='work_items')
    op.drop_index('idx_work_item_sort_project', table_name='work_items')
    op.drop_column('work_items', 'sort_order')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work_items', sa.Column('sort_order', sa.INTEGER(), nullable=True))
    op.create_index('idx_work_item_sort_project', 'work_items', ['project_id', 'kind', 'sort_order'], unique=False)
    op.create_index('idx_work_item_sort_parent', 'work_items', ['parent_id', 'sort_order'], unique=False)
    op.alter_column('work_items', 'estimated_hours',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('work_items', 'label_path',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'avatar_key',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'phone',
               existing_type=sa.String(length=30),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'full_name',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint(op.f('fk_projects_creator_id_users'), 'projects', type_='foreignkey')
    op.alter_column('projects', 'label_path',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('projects', 'priority',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('project_non_dev_works', 'work_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'other_work'"))
    op.drop_index(op.f('ix_operation_logs_id'), table_name='operation_logs')
    op.drop_column('operation_logs', 'new_value')
    op.drop_column('operation_logs', 'old_value')
    op.drop_column('operation_logs', 'field_name')
    # ### end Alembic commands ###