"""fix creator_id not null

Revision ID: fix_creator_id_not_null
Revises: 
Create Date: 2025-12-17 09:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fix_creator_id_not_null'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 确保 projects 表中的 creator_id 字段不为空
    # 首先更新所有 NULL 值为默认值（这里使用 1，假设是管理员用户ID）
    op.execute("UPDATE projects SET creator_id = 1 WHERE creator_id IS NULL")
    
    # 然后修改列定义使其不为空
    # 注意：SQLite 不支持直接修改列定义，所以我们需要重建表
    # 但在实际环境中，我们会使用更复杂的迁移策略
    # 这里我们只是添加一个约束来确保将来不会有 NULL 值
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.alter_column('creator_id', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.alter_column('creator_id', nullable=True)
    # ### end Alembic commands ###